### ISSUE TITLE
Distributing trials across participants

### ISSUE THREAD

**Issue by fredcallaway** [hsharrison/experimentator#23]
Basically, I want to do a latin square for the stimuli assignment, not the ordering.

For example, say I have the design:
```yaml
  - name: participant
  - name: trial
    ivs:
      layout: [A, B]
      goes_in: [1, 0]
```

By default this gives me one participant with 4 trials:
```
Subj 1: A1 A0 B1 B0
```
 But let's say I want to impose a restriction that each participant only see each iv value once. That is, I want (ignoring ordering for now):
```
Subj1: A1 B0
Subj2: A0 B1
```

I was planning to implement this myself, but I figured I'd check in with you first. I think we can modify `design_matrix` to allow a 3d array, where the extra (first) dimension will define the different possible design matrices that a subject could be assigned to. Assignment will be done by adding an extra iv to participant, similar to how counterbalancing is implemented. 
```yaml
  - name: participant
  - name: trial
    ivs:
      layout: [A, B]
      hit: [0, 1]
    desgin_matrix:
      -
        - [1, 1]
        - [0, 0]
      -
        - [0, 1]
        - [1, 0]
```

Step 2 will be to implement common choices of 3d design matrices, such as the latin squares in my example. I think an interface similar to the one to `Ordering` makes sense. I wrote up the basic logic [here](https://gist.github.com/fredcallaway/b9e505c48c0d0b62504c175a45e6cf01).
